### ISSUE TITLE
Remove redness from positive output

### ISSUE THREAD

**Issue by alexmuller** [alphagov/cheapseats#50]
When the tests succeed, I see:

> ✔ 18 stubs passed (green)
> ✘ 0 stubs failed (red)

Can we make turn that red into black or something when there are 0 failures? My eyes immediately jump to red console output.

**Comment by deanwilson** [comment]
Thank you for raising this PR but as this system is now in reactive maintenance mode this change is unlikely to be made. And hasn't been in the 5 years since it was raised.

👋 @alexmuller

**Comment by alexmuller** [comment]
👍
